title: Rachel Hill-Tsarpelas
logo: "images/image.png?raw=true"
description: Data Analyst | Python • SQL • Power BI | Linguistics
About Me: 
My journey to Data Analysis might not be the traditional route, but it definitely has been a very organic one. In every role I’ve held, I’ve been driven to go beyond the surface tasks and analyze how it fits in the context of the big picture, to gain greater insights and understanding.

I began my career teaching English, but immediately felt hemmed in by prestige and prescriptivism. English is used all over the world in many different but equally valid varieties. This sparked a deeper curiosity in me about language, not as a set of rules to follow, but as a system and especially multiple languages as a system within one person. That curiosity led me to a Master’s degree in European Linguistics at the University of Freiburg, where in addition to my studies, I began work as a research assistant with large English Corpora. Analyzing real world language data, which had no problem contradicting textbook rules, showed me first hand what a powerful tool large data sets can be in reflecting reality. 

After my studies, I worked as an editor in Hueber, managing big textbook projects with lots of moving parts, actors  and various deadlines.  While I thrived in the complexity of project management,  I missed the data-driven analysis I had grown to love. Too often, decisions were guided by preference over evidence.
During my parental leave, I had time to reassess my career and understand where this natural analytical tendency was leading me. I made a conscious shift toward tech and data analytics. Learning to code was just another language at the end of the day. Using data to uncover patterns, challenge assumptions and add it to the general understanding is where my strengths align. Moreover, my background positions me as a bridge between analysis and language, able to communicate complex processes and insights clearly across languages and formats. My core skill set includes Python-based data analysis in Jupyter Notebooks, data querying with SQL, and dashboarding in Power BI, alongside a growing focus on large language models informed by my linguistics background.



<a href="www.linkedin.com/in/rachel-hill-data-analyst" >View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

google_analytics: UA-000000-0

